//! Production nodes for the video pipeline
//!
//! Each node implements the Orichalcum `AsyncNodeLogic` trait and represents
//! a stage in the video production pipeline.

pub mod asset_collector;
pub mod publisher;
pub mod scheduler;
pub mod script_writer;
pub mod seo_optimizer;
pub mod strategy;
pub mod thumbnail;
pub mod tts;
pub mod video_assembler;

// Re-exports
pub use asset_collector::AssetCollectorLogic;
pub use publisher::PublisherLogic;
pub use scheduler::SchedulerLogic;
pub use script_writer::ScriptWriterLogic;
pub use seo_optimizer::SEOOptimizerLogic;
pub use strategy::StrategyLogic;
pub use thumbnail::ThumbnailLogic;
pub use tts::TTSLogic;
pub use video_assembler::VideoAssemblerLogic;

use serde::{Deserialize, Serialize};

/// Shared data structures used across nodes

/// Topic brief generated by the Strategy node
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicBrief {
    /// Unique ID for this production
    pub video_id: uuid::Uuid,
    /// Main topic/title idea
    pub topic: String,
    /// Detailed description of what to cover
    pub description: String,
    /// Target duration in minutes
    pub target_duration_minutes: u32,
    /// Primary wisdom source category
    pub primary_source: WisdomSource,
    /// Secondary sources to draw from
    pub secondary_sources: Vec<WisdomSource>,
    /// Target keywords for SEO
    pub target_keywords: Vec<String>,
    /// Hook angle/approach
    pub hook_angle: String,
    /// Scheduled publish time
    pub scheduled_publish: Option<chrono::DateTime<chrono::Utc>>,
    /// Whether this was an automatically scheduled video
    #[serde(default = "default_true")]
    pub is_autonomous: bool,
}

fn default_true() -> bool { true }

/// Wisdom source categories
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum WisdomSource {
    /// Biblical wisdom (Proverbs, Ecclesiastes, Psalms, Gospels, Epistles)
    Bible { book: String },
    /// Stoic philosophy (Marcus Aurelius, Seneca, Epictetus)
    Stoicism { author: String },
    /// General philosophy (Aristotle, Nietzsche, Camus, etc.)
    Philosophy { author: String },
    /// Biographical content
    Biography { subject: String },
    /// Psychology classics (Frankl, Jung, etc.)
    Psychology { author: String },
}

impl WisdomSource {
    pub fn category_name(&self) -> &'static str {
        match self {
            WisdomSource::Bible { .. } => "Scripture",
            WisdomSource::Stoicism { .. } => "Stoicism",
            WisdomSource::Philosophy { .. } => "Philosophy",
            WisdomSource::Biography { .. } => "Biography",
            WisdomSource::Psychology { .. } => "Psychology",
        }
    }
}

/// Script structure with timing markers
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Script {
    /// The video this script is for
    pub video_id: uuid::Uuid,
    /// Opening hook (first 30 seconds)
    pub hook: ScriptSection,
    /// Main content sections
    pub sections: Vec<ScriptSection>,
    /// Closing call-to-action
    pub cta: ScriptSection,
    /// Total estimated duration in seconds
    pub total_duration_seconds: u32,
    /// Full script text (for TTS)
    pub full_text: String,
    /// Index of the section chosen for Shorts (0 = hook, 1..N = sections, N+1 = cta)
    pub shorts_candidate_index: Option<usize>,
}

/// A section of the script
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScriptSection {
    /// Section title (for internal reference)
    pub title: String,
    /// The narration text
    pub narration: String,
    /// Estimated duration in seconds
    pub duration_seconds: u32,
    /// Visual suggestions for B-roll
    pub visual_suggestions: Vec<String>,
    /// Atmospheric mood (e.g., "somber", "hopeful", "intense")
    #[serde(default)]
    pub mood: String,
    /// SFX triggers for this section
    #[serde(default)]
    pub sfx_triggers: Vec<SFXTrigger>,
}

/// A sound effect trigger
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SFXTrigger {
    /// Type of sound (texture, punctuation)
    pub sfx_type: String,
    /// Sound description (e.g., "thunder", "quill_scratching")
    pub sound: String,
    /// Relative timing (0.0 to 1.0) within the section
    pub relative_time: f32,
    /// Volume multiplier (0.0 to 1.0)
    pub volume: f32,
}

/// Audio timing data from TTS
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AudioTiming {
    /// Path to the audio file in S3
    pub audio_path: String,
    /// Total duration in seconds
    pub total_duration_seconds: f64,
    /// Timing markers for each section
    pub section_timings: Vec<SectionTiming>,
}

/// Timing for a single section
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SectionTiming {
    pub section_title: String,
    pub start_seconds: f64,
    pub end_seconds: f64,
}

/// Manifest of collected assets
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetManifest {
    /// Video ID
    pub video_id: uuid::Uuid,
    /// Background music track
    pub background_music: Option<String>,
    /// Assets organized by section
    pub section_assets: Vec<SectionAssets>,
}

/// Assets for a single section
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SectionAssets {
    pub section_title: String,
    /// Video clips (B-roll)
    pub video_clips: Vec<AssetFile>,
    /// Static images
    pub images: Vec<AssetFile>,
}

/// A single asset file
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetFile {
    /// Path in S3
    pub path: String,
    /// Source (pexels, stable_diffusion, etc.)
    pub source: String,
    /// Duration in seconds (for video clips)
    pub duration_seconds: Option<f64>,
    /// Description/alt text
    pub description: String,
}

/// SEO metadata for the video
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SEOMetadata {
    pub video_id: uuid::Uuid,
    /// Optimized title
    pub title: String,
    /// Full description with timestamps
    pub description: String,
    /// Tags
    pub tags: Vec<String>,
    /// Chapter markers
    pub chapters: Vec<Chapter>,
    /// Thumbnail variants
    pub thumbnail_paths: Vec<String>,
}

/// Chapter marker for description
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Chapter {
    pub title: String,
    pub timestamp_seconds: u32,
}

// ============================================================================
// Script Self-Improvement Types
// ============================================================================

/// Evaluation of a single script by the judge LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScriptEvaluation {
    pub overall_score: f32,
    pub criteria: CriteriaScores,
    pub strengths: Vec<String>,
    pub weaknesses: Vec<String>,
    pub ai_telltale_signs: Vec<String>,
    pub specific_improvements: Vec<SpecificImprovement>,
}

/// Individual criterion scores (1-10 scale)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CriteriaScores {
    /// Does the first 30 seconds create an irresistible urge to keep watching?
    pub hook_strength: CriterionScore,
    /// Does the rhythm vary? Are there retention hooks every 2-3 minutes?
    pub pacing_retention: CriterionScore,
    /// Are sources woven naturally into the narrative?
    pub wisdom_integration: CriterionScore,
    /// Does this sound like a real person sharing hard-won insights?
    pub authenticity: CriterionScore,
    /// Is the word count close to target?
    pub duration_accuracy: CriterionScore,
    /// Does the closing feel earned?
    pub cta_quality: CriterionScore,
    /// Absence of AI telltale signs
    pub ai_detection: CriterionScore,
}

/// Score for a single criterion
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CriterionScore {
    pub score: f32,
    pub notes: String,
}

/// A specific improvement suggestion with location
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecificImprovement {
    /// Where in the script (e.g., "Section 2, paragraph 3")
    pub location: String,
    /// What's wrong
    pub issue: String,
    /// How to fix it
    pub suggestion: String,
}

/// A script candidate with its evaluation
#[derive(Debug, Clone)]
pub struct ScoredScript {
    pub script: Script,
    pub evaluation: ScriptEvaluation,
    pub iteration: u32,
    pub candidate_index: Option<u32>,
    /// Database ID of the evaluation record (for marking as selected)
    pub evaluation_id: Option<i32>,
}
