//! Production nodes for the video pipeline
//!
//! Each node implements the Orichalcum `AsyncNodeLogic` trait and represents
//! a stage in the video production pipeline.

pub mod asset_collector;
pub mod publisher;
pub mod scheduler;
pub mod script_writer;
pub mod seo_optimizer;
pub mod strategy;
pub mod thumbnail;
pub mod tts;
pub mod video_assembler;

// Re-exports
pub use asset_collector::AssetCollectorLogic;
pub use publisher::PublisherLogic;
pub use scheduler::SchedulerLogic;
pub use script_writer::ScriptWriterLogic;
pub use seo_optimizer::SEOOptimizerLogic;
pub use strategy::StrategyLogic;
pub use thumbnail::ThumbnailLogic;
pub use tts::TTSLogic;
pub use video_assembler::VideoAssemblerLogic;

use serde::{Deserialize, Serialize};

/// Shared data structures used across nodes

/// Topic brief generated by the Strategy node
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicBrief {
    /// Unique ID for this production
    pub video_id: uuid::Uuid,
    /// Main topic/title idea
    pub topic: String,
    /// Detailed description of what to cover
    pub description: String,
    /// Target duration in minutes
    pub target_duration_minutes: u32,
    /// Primary wisdom source category
    pub primary_source: WisdomSource,
    /// Secondary sources to draw from
    pub secondary_sources: Vec<WisdomSource>,
    /// Target keywords for SEO
    pub target_keywords: Vec<String>,
    /// Hook angle/approach
    pub hook_angle: String,
    /// Scheduled publish time
    pub scheduled_publish: Option<chrono::DateTime<chrono::Utc>>,
}

/// Wisdom source categories
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum WisdomSource {
    /// Biblical wisdom (Proverbs, Ecclesiastes, Psalms, Gospels, Epistles)
    Bible { book: String },
    /// Stoic philosophy (Marcus Aurelius, Seneca, Epictetus)
    Stoicism { author: String },
    /// General philosophy (Aristotle, Nietzsche, Camus, etc.)
    Philosophy { author: String },
    /// Biographical content
    Biography { subject: String },
    /// Psychology classics (Frankl, Jung, etc.)
    Psychology { author: String },
}

impl WisdomSource {
    pub fn category_name(&self) -> &'static str {
        match self {
            WisdomSource::Bible { .. } => "Scripture",
            WisdomSource::Stoicism { .. } => "Stoicism",
            WisdomSource::Philosophy { .. } => "Philosophy",
            WisdomSource::Biography { .. } => "Biography",
            WisdomSource::Psychology { .. } => "Psychology",
        }
    }
}

/// Script structure with timing markers
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Script {
    /// The video this script is for
    pub video_id: uuid::Uuid,
    /// Opening hook (first 30 seconds)
    pub hook: ScriptSection,
    /// Main content sections
    pub sections: Vec<ScriptSection>,
    /// Closing call-to-action
    pub cta: ScriptSection,
    /// Total estimated duration in seconds
    pub total_duration_seconds: u32,
    /// Full script text (for TTS)
    pub full_text: String,
}

/// A section of the script
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScriptSection {
    /// Section title (for internal reference)
    pub title: String,
    /// The narration text
    pub narration: String,
    /// Estimated duration in seconds
    pub duration_seconds: u32,
    /// Visual suggestions for B-roll
    pub visual_suggestions: Vec<String>,
}

/// Audio timing data from TTS
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AudioTiming {
    /// Path to the audio file in S3
    pub audio_path: String,
    /// Total duration in seconds
    pub total_duration_seconds: f64,
    /// Timing markers for each section
    pub section_timings: Vec<SectionTiming>,
}

/// Timing for a single section
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SectionTiming {
    pub section_title: String,
    pub start_seconds: f64,
    pub end_seconds: f64,
}

/// Manifest of collected assets
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetManifest {
    /// Video ID
    pub video_id: uuid::Uuid,
    /// Background music track
    pub background_music: Option<String>,
    /// Assets organized by section
    pub section_assets: Vec<SectionAssets>,
}

/// Assets for a single section
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SectionAssets {
    pub section_title: String,
    /// Video clips (B-roll)
    pub video_clips: Vec<AssetFile>,
    /// Static images
    pub images: Vec<AssetFile>,
}

/// A single asset file
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetFile {
    /// Path in S3
    pub path: String,
    /// Source (pexels, stable_diffusion, etc.)
    pub source: String,
    /// Duration in seconds (for video clips)
    pub duration_seconds: Option<f64>,
    /// Description/alt text
    pub description: String,
}

/// SEO metadata for the video
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SEOMetadata {
    pub video_id: uuid::Uuid,
    /// Optimized title
    pub title: String,
    /// Full description with timestamps
    pub description: String,
    /// Tags
    pub tags: Vec<String>,
    /// Chapter markers
    pub chapters: Vec<Chapter>,
    /// Thumbnail variants
    pub thumbnail_paths: Vec<String>,
}

/// Chapter marker for description
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Chapter {
    pub title: String,
    pub timestamp_seconds: u32,
}
